### ISSUE TITLE
Pixiv downloader requests end with 403

### ISSUE THREAD

**Issue by LilyKensa** [ShiroNexo/nexo-aio-downloader#4]
The Pixiv downloader no longer works

```
Pixiv Downloader: AxiosError: Request failed with status code 403
```

The request sent to get the meta got rejected.

I think Pixiv might have added some more cookie?  
There are now `privacy_policy_agreement` and `privacy_policy_notification`, which I think is new and will expire like after 2026.

**Comment by ShiroNexo** [comment]
![image](https://github.com/user-attachments/assets/78b5ad4b-b3a8-4697-8f90-0087af35125b)
Everything is working smoothly here, perhaps your IP has been blocked by Pixiv.

**Comment by LilyKensa** [comment]
Welp, I don't actually know, I'll check it out later
My server is under the same network as my laptop (using the same global IP,) and my laptop is able to browse Pixiv

**Comment by LilyKensa** [comment]
Bro, after doing nothing, it started working again

![image](https://github.com/user-attachments/assets/93313238-f0aa-4183-96c2-84b6593b75f9)
